---
abstract: 'Parse and format Indonesian dates'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0.98
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-Indonesian
requires:
  DateTime: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/DateTime-Format-Indonesian
  repository: http://github.com/sharyanto/perl-DateTime-Format-Indonesian
version: 0.01
